version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.2

jobs:
  lint:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout
      - run: composer install && composer phpcs

workflows:
  lint-deploy:
    jobs:
      - lint
      - approval-for-deploy-tested-up-to-bump:
          requires:
            - lint
          type: approval
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
      - wp-svn/deploy:
          context: genesis-svn
          requires:
            - lint
